# Copyright 2024-2026 Glenn J. White (The Open University / RAL Space)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
ASTRA Live — Cognitive Core
Unified cognitive architecture for scientific discovery.

Paradigm Shift: From tool-based to cognition-based architecture.

The Cognitive Core integrates:
1. Dynamic Knowledge Graph (semantic brain)
2. Neuro-Symbolic Integration Engine (unified reasoning)
3. Meta-Cognitive Architecture (self-awareness)
4. All existing ASTRA capabilities

This creates a unified intelligence capable of:
- Perceiving multi-modal data
- Reasoning across neural and symbolic paradigms
- Maintaining coherent knowledge representation
- Monitoring its own reasoning
- Improving through experience
- Generating novel scientific insights

This is a significant step toward Scientific AGI.
"""
import numpy as np
from typing import Dict, List, Tuple, Optional, Any, Union
from dataclasses import dataclass, field
from enum import Enum
import json
from datetime import datetime

# Import ASTRA's existing capabilities
from .knowledge_graph import (
    DynamicKnowledgeGraph, Entity, EntityType, Relation, RelationType
)
from .neuro_symbolic_engine import (
    NeuroSymbolicIntegrator, ReasoningMode, NeuroSymbolicPrediction
)
from .meta_cognitive_architecture import (
    MetaCognitiveArchitecture, ReasoningTraceType, CognitiveState
)

# Import existing ASTRA modules
try:
    from .theory_data_validator import TheoryDataValidator, TheoryPrediction
    from .unified_discovery_engine import UnifiedDiscoveryEngine, DiscoveryMode
    from .experiment_design_engine import ExperimentDesignEngine
    ASTRA_MODULES_AVAILABLE = True
except ImportError:
    ASTRA_MODULES_AVAILABLE = False


class CognitiveMode(Enum):
    """Modes of cognitive processing."""
    PERCEPTION = "perception"           # Taking in information
    REASONING = "reasoning"             # Processing and inference
    REFLECTION = "reflection"           # Self-monitoring
    LEARNING = "learning"               # Updating knowledge
    GENERATION = "generation"           # Creating new insights
    VALIDATION = "validation"           # Testing and verification


@dataclass
class Perception:
    """A perceptual input from multi-modal data."""
    perception_id: str
    data: Any  # Could be numerical, image, spectrum, text
    data_type: str  # "numerical", "image", "spectrum", "text"
    features: Dict[str, Any]
    confidence: float
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class CognitiveInsight:
    """A scientific insight generated by the cognitive core."""
    insight_id: str
    insight_type: str  # "pattern", "causal", "theoretical", "anomaly"
    description: str
    confidence: float
    evidence: List[str]  # IDs of supporting evidence
    reasoning_chain: List[str]  # How was this derived?
    predictions: List[str]  # What does this predict?
    uncertainty: float  # Quantified uncertainty
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class ScientificDiscovery:
    """A complete scientific discovery."""
    discovery_id: str
    title: str
    discovery_type: str  # "empirical", "theoretical", "integrated"
    insights: List[str]  # IDs of insights
    theoretical_framework: Optional[str]  # Theory ID
    empirical_support: List[str]  # Evidence IDs
    confidence: float
    significance: float  # 0-1, scientific impact
    novelty: float  # 0-1, how novel?
    validity: float  # 0-1, how well validated?
    explanation: str  # Human-interpretable explanation
    next_steps: List[str]  # What to do next?
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


class CognitiveCore:
    """
    Unified cognitive architecture for scientific discovery.

    This is the brain of ASTRA - orchestrating all cognitive capabilities.

    Architecture:
    ┌─────────────────────────────────────────────────────────────┐
    │                    COGNITIVE CORE                           │
    ├─────────────────────────────────────────────────────────────┤
    │                                                               │
    │  ┌─────────────┐  ┌──────────────┐  ┌──────────────┐       │
    │  │PERCEPTION   │→ │  REASONING   │→ │  REFLECTION  │       │
    │  │             │  │              │  │              │       │
    │  │Multi-Modal  │  │Neuro-Symbolic│  │Meta-Cognitive│       │
    │  │Understanding│  │Integration   │  │Monitoring    │       │
    │  └─────────────┘  └──────────────┘  └──────────────┘       │
    │          ↓                 ↓                 ↓              │
    │  ┌───────────────────────────────────────────────────┐    │
    │  │            DYNAMIC KNOWLEDGE GRAPH                 │    │
    │  │  (Semantic Brain - integrates all knowledge)      │    │
    │  └───────────────────────────────────────────────────┘    │
    │                                                               │
    │  Output: Scientific discoveries with explanations           │
    └─────────────────────────────────────────────────────────────┘
    """

    def __init__(self):
        # Core cognitive systems
        self.knowledge_graph = DynamicKnowledgeGraph()
        self.neuro_symbolic = NeuroSymbolicIntegrator()
        self.metacognition = MetaCognitiveArchitecture()

        # Existing ASTRA modules (if available)
        if ASTRA_MODULES_AVAILABLE:
            self.theory_validator = TheoryDataValidator()
            self.unified_discovery = UnifiedDiscoveryEngine()
            self.experiment_designer = ExperimentDesignEngine()

        # Cognitive state
        self.current_mode = CognitiveMode.PERCEPTION
        self.current_focus = None  # What is the system focused on?

        # Memory
        self.perceptions: List[Perception] = []
        self.insights: List[CognitiveInsight] = []
        self.discoveries: List[ScientificDiscovery] = []

        # Performance tracking
        self.discovery_count = 0
        self.insight_count = 0

    def perceive(self, data: Any, data_type: str, features: Dict[str, Any] = None
                ) -> Perception:
        """
        Take in perceptual information from multi-modal data.

        This is the entry point for all data into the cognitive system.
        """
        # Create perception
        perception_id = f"perception_{len(self.perceptions)}"
        perception = Perception(
            perception_id=perception_id,
            data=data,
            data_type=data_type,
            features=features or {},
            confidence=0.8  # Default confidence
        )

        self.perceptions.append(perception)

        # Start meta-cognitive monitoring
        trace_id = self.metacognition.start_reasoning_trace(
            f"Process {data_type} data",
            ReasoningTraceType.DATA_ANALYSIS
        )

        # Update cognitive state
        self.current_mode = CognitiveMode.PERCEPTION
        self.current_focus = perception_id

        return perception

    def reason(self, perception_id: str, reasoning_mode: CognitiveMode = CognitiveMode.REASONING
              ) -> List[CognitiveInsight]:
        """
        Reason about perceptions to generate insights.

        This is where the cognitive work happens - integrating perception,
        knowledge, reasoning, and self-monitoring.
        """
        if perception_id >= len(self.perceptions):
            return []

        perception = self.perceptions[perception_id]

        # Update cognitive state
        self.current_mode = reasoning_mode
        self.metacognition.current_state = CognitiveState.NORMAL

        # Start reasoning trace
        trace_id = self.metacognition.start_reasoning_trace(
            f"Reason about {perception.data_type} data",
            ReasoningTraceType.DATA_ANALYSIS
        )

        insights = []

        # 1. Neural pattern discovery
        if isinstance(perception.data, np.ndarray) and perception.data_type == "numerical":
            neural_disc, symbolic_form = self.neuro_symbolic.discover_and_formalize(
                perception.data,
                list(perception.features.keys()),
                ReasoningMode.INTEGRATED
            )

            # Create insights from neural discoveries
            for disc in neural_disc:
                insight_id = f"insight_{len(self.insights)}"
                insight = CognitiveInsight(
                    insight_id=insight_id,
                    insight_type=disc.pattern_type,
                    description=disc.pattern_description,
                    confidence=disc.confidence,
                    evidence=[perception_id],
                    reasoning_chain=[
                        f"Neural discovery: {disc.pattern_type}",
                        f"Features: {', '.join(disc.features)}",
                        f"Confidence: {disc.confidence:.2f}"
                    ],
                    predictions=[],
                    uncertainty=1.0 - disc.confidence
                )
                insights.append(insight)
                self.insights.append(insight)

                # Log to metacognition
                self.metacognition.add_reasoning_step(
                    trace_id=trace_id,
                    operation="neural_discovery",
                    inputs={"features": disc.features},
                    outputs={"pattern": disc.pattern_type},
                    confidence=disc.confidence,
                    reasoning_context=["Neural pattern detection"]
                )

            # Create insights from symbolic formalizations
            for form in symbolic_form:
                insight_id = f"insight_{len(self.insights)}"
                insight = CognitiveInsight(
                    insight_id=insight_id,
                    insight_type=form.formalization_type,
                    description=form.symbolic_form,
                    confidence=form.validation_score,
                    evidence=[perception_id],
                    reasoning_chain=[
                        f"Symbolic formalization: {form.formalization_type}",
                        f"Form: {form.symbolic_form}",
                        f"Validation: {form.validation_score:.2f}"
                    ],
                    predictions=[],
                    uncertainty=1.0 - form.validation_score
                )
                insights.append(insight)
                self.insights.append(insight)

        # 2. Knowledge graph reasoning
        # Find related entities in knowledge graph
        if perception.features:
            for feature_name, feature_value in perception.features.items():
                # Query knowledge graph for related concepts
                related = self.knowledge_graph.query(
                    query_type="entity",
                    name=feature_name,
                    min_confidence=0.5
                )

                if related:
                    # Create insight from knowledge graph
                    insight_id = f"insight_{len(self.insights)}"
                    insight = CognitiveInsight(
                        insight_id=insight_id,
                        insight_type="semantic",
                        description=f"Knowledge graph relation found for {feature_name}",
                        confidence=0.7,
                        evidence=[perception_id],
                        reasoning_chain=[
                            f"Query: {feature_name}",
                            f"Found {len(related)} related entities"
                        ],
                        predictions=[],
                        uncertainty=0.3
                    )
                    insights.append(insight)
                    self.insights.append(insight)

        # 3. End reasoning trace
        self.metacognition.end_reasoning_trace(
            trace_id=trace_id,
            outcome=f"Generated {len(insights)} insights",
            success=len(insights) > 0
        )

        return insights

    def reflect(self, focus_discovery: Optional[str] = None) -> Dict[str, Any]:
        """
        Reflect on recent performance and generate improvements.

        This is meta-cognition - the system thinking about itself.
        """
        self.current_mode = CognitiveMode.REFLECTION
        self.metacognition.current_state = CognitiveState.REFLECTING

        # Generate reflection
        reflection = self.metacognition.reflect_on_performance(n_recent_traces=20)

        # Update knowledge based on reflection
        if reflection:
            # Apply strategy changes
            for change in reflection.strategy_changes:
                # Update knowledge graph with new insights
                pass

        # Get self-awareness report
        self_awareness = self.metacognition.get_self_awareness_report()

        # Identify knowledge gaps
        knowledge_gaps = self.knowledge_graph.find_knowledge_gaps()

        return {
            'reflection': reflection,
            'self_awareness': self_awareness,
            'knowledge_gaps': knowledge_gaps,
            'cognitive_state': self.metacognition.current_state.value
        }

    def learn(self, insights: List[CognitiveInsight]) -> List[str]:
        """
        Learn from insights and update knowledge representation.

        This is where the system updates its understanding based on
        what it has discovered.
        """
        self.current_mode = CognitiveMode.LEARNING

        updated_entities = []

        for insight in insights:
            # Create entities in knowledge graph from insights
            if insight.insight_type == "pattern":
                # Create pattern entity
                entity = self.knowledge_graph.add_entity(
                    name=insight.description[:50],
                    entity_type=EntityType.CONCEPT,
                    domain="discovered_patterns",
                    properties={
                        "confidence": insight.confidence,
                        "uncertainty": insight.uncertainty
                    },
                    confidence=insight.confidence
                )
                updated_entities.append(entity.id)

            elif insight.insight_type == "correlation":
                # Create relation between correlated features
                if len(insight.reasoning_chain) > 0:
                    # Parse reasoning chain to extract features
                    # (This is simplified)
                    pass

        # Trigger belief propagation in knowledge graph
        # (This updates confidences across the network)

        return updated_entities

    def discover(self, data: Any, data_type: str, features: Dict[str, Any]
                ) -> ScientificDiscovery:
        """
        Complete discovery pipeline: perceive → reason → learn → discover.

        This is the main entry point for scientific discovery.
        """
        # 1. Perceive
        perception = self.perceive(data, data_type, features)

        # 2. Reason
        insights = self.reason(perception.perception_id)

        # 3. Learn
        learned_entities = self.learn(insights)

        # 4. Generate discovery
        if insights:
            discovery_id = f"discovery_{self.discovery_count}"
            self.discovery_count += 1

            # Combine insights into coherent discovery
            high_confidence_insights = [i for i in insights if i.confidence > 0.6]

            if high_confidence_insights:
                discovery = ScientificDiscovery(
                    discovery_id=discovery_id,
                    title=f"Discovery from {data_type} analysis",
                    discovery_type="empirical",
                    insights=[i.insight_id for i in high_confidence_insights],
                    theoretical_framework=None,
                    empirical_support=[perception.perception_id],
                    confidence=np.mean([i.confidence for i in high_confidence_insights]),
                    significance=0.7,  # Simplified
                    novelty=0.6,  # Simplified
                    validity=np.mean([i.confidence for i in high_confidence_insights]),
                    explanation=self._generate_explanation(high_confidence_insights),
                    next_steps=self._generate_next_steps(high_confidence_insights)
                )

                self.discoveries.append(discovery)

                return discovery

        return None

    def _generate_explanation(self, insights: List[CognitiveInsight]) -> str:
        """Generate human-interpretable explanation from insights."""
        if not insights:
            return "No significant insights generated."

        explanation_parts = [
            f"Analysis generated {len(insights)} insights:",
        ]

        for insight in insights[:3]:  # Top 3
            explanation_parts.append(
                f"- {insight.description} (confidence: {insight.confidence:.2f})"
            )

        return " | ".join(explanation_parts)

    def _generate_next_steps(self, insights: List[CognitiveInsight]) -> List[str]:
        """Generate suggested next steps based on insights."""
        next_steps = []

        for insight in insights:
            if insight.insight_type == "correlation":
                next_steps.append(f"Investigate causal mechanism for {insight.description}")
            elif insight.insight_type == "cluster":
                next_steps.append(f"Analyze members of {insight.description} in detail")
            elif insight.insight_type == "anomaly":
                next_steps.append(f"Verify anomaly: {insight.description}")

        return next_steps[:5]  # Top 5

    def unify_theory_and_data(self, theory_description: str, data: np.ndarray
                             ) -> Dict[str, Any]:
        """
        Unify theoretical and empirical discovery.

        This integrates ASTRA's existing theory-data validation with
        the new cognitive architecture.
        """
        if not ASTRA_MODULES_AVAILABLE:
            return {"error": "ASTRA modules not available"}

        # 1. Create theory prediction
        theory = TheoryPrediction(
            theory_name=theory_description,
            prediction_type="qualitative",
            mathematical_form=theory_description,
            variables={},
            parameters={},
            confidence=0.7
        )

        # 2. Validate against data
        validation = self.theory_validator.validate_theoretical_prediction(
            theory, data, {}
        )

        # 3. Generate insights from validation
        insights = []

        insight = CognitiveInsight(
            insight_id=f"validation_{len(self.insights)}",
            insight_type="validation",
            description=f"Theory '{theory_description}' validation: {validation.status.value}",
            confidence=validation.agreement_score,
            evidence=[],
            reasoning_chain=[
                f"Theory: {theory_description}",
                f"Status: {validation.status.value}",
                f"Agreement: {validation.agreement_score:.2f}"
            ],
            predictions=[],
            uncertainty=1.0 - validation.agreement_score
        )
        insights.append(insight)
        self.insights.append(insight)

        return {
            'validation_result': validation,
            'insights': [i.insight_id for i in insights],
            'theory_supported': validation.status.value == "VALIDATED"
        }

    def design_experiments(self, n_proposals: int = 3) -> List[Dict]:
        """
        Design experiments to test current theories and fill knowledge gaps.

        Integrates ASTRA's existing experiment design with cognitive architecture.
        """
        if not ASTRA_MODULES_AVAILABLE:
            return []

        # Get knowledge gaps
        gaps = self.knowledge_graph.find_knowledge_gaps()

        if gaps:
            # Prioritize gaps
            high_priority_gaps = [g for g in gaps if g.priority > 0.7][:n_proposals]

            # Generate experiment proposals
            proposals = []

            for gap in high_priority_gaps:
                proposal = {
                    'gap_type': gap.gap_type,
                    'description': gap.description,
                    'priority': gap.priority,
                    'suggested_experiments': gap.suggestions
                }
                proposals.append(proposal)

            return proposals

        return []

    def get_cognitive_summary(self) -> Dict[str, Any]:
        """Get comprehensive summary of cognitive state."""
        return {
            'cognitive_mode': self.current_mode.value,
            'perceptions': len(self.perceptions),
            'insights': len(self.insights),
            'discoveries': len(self.discoveries),
            'knowledge_graph_stats': self.knowledge_graph.get_statistics(),
            'neuro_symbolic_stats': self.neuro_symbolic.get_performance_summary(),
            'metacognitive_report': self.metacognition.get_self_awareness_report()
        }

    def explain_discovery(self, discovery_id: str, audience_level: str = "expert"
                         ) -> Dict[str, str]:
        """
        Generate explanation for a discovery at different audience levels.

        This is key for explainable AI.
        """
        if discovery_id >= len(self.discoveries):
            return None

        discovery = self.discoveries[discovery_id]

        explanations = {
            "expert": self._explain_for_expert(discovery),
            "student": self._explain_for_student(discovery),
            "public": self._explain_for_public(discovery)
        }

        return {
            'audience_level': audience_level,
            'explanation': explanations.get(audience_level, explanations["expert"]),
            'all_explanations': explanations
        }

    def _explain_for_expert(self, discovery: ScientificDiscovery) -> str:
        """Generate expert-level explanation."""
        return (f"{discovery.title}. "
                f"Discovery type: {discovery.discovery_type}, "
                f"Confidence: {discovery.confidence:.2f}, "
                f"Significance: {discovery.significance:.2f}, "
                f"Novelty: {discovery.novelty:.2f}, "
                f"Validity: {discovery.validity:.2f}. "
                f"Details: {discovery.explanation}")

    def _explain_for_student(self, discovery: ScientificDiscovery) -> str:
        """Generate student-level explanation."""
        return (f"We discovered {discovery.title.lower()}. "
                f"This is {discovery.discovery_type} evidence with "
                f"{discovery.confidence:.0%} confidence. "
                f"The significance is {discovery.significance:.0%} and "
                f"the novelty is {discovery.novelty:.0%}.")

    def _explain_for_public(self, discovery: ScientificDiscovery) -> str:
        """Generate public-level explanation."""
        return (f"ASTRA discovered {discovery.title.lower()}. "
                f"This finding has high scientific importance "
                f"and helps us understand the universe better.")


# Demonstration
if __name__ == "__main__":
    print("=" * 80)
    print("COGNITIVE CORE - Unified Architecture for Scientific Discovery")
    print("=" * 80)

    core = CognitiveCore()

    print("\n1. COMPLETE DISCOVERY PIPELINE")
    print("-" * 80)

    # Create sample data
    np.random.seed(42)
    n_samples = 100
    x = np.random.uniform(0.1, 10, n_samples)
    y = 2 * x ** 1.5 + np.random.normal(0, 0.5, n_samples)
    data = np.column_stack([x, y])
    features = {"mass": x, "luminosity": y}

    # Discover
    discovery = core.discover(data, "numerical", features)

    if discovery:
        print(f"\nDiscovery: {discovery.title}")
        print(f"Type: {discovery.discovery_type}")
        print(f"Confidence: {discovery.confidence:.2f}")
        print(f"Significance: {discovery.significance:.2f}")
        print(f"Novelty: {discovery.novelty:.2f}")
        print(f"Validity: {discovery.validity:.2f}")
        print(f"\nExplanation: {discovery.explanation}")

        if discovery.next_steps:
            print(f"\nNext Steps:")
            for step in discovery.next_steps:
                print(f"  • {step}")

        # Explain at different levels
        print("\n2. EXPLAINABLE DISCOVERY")
        print("-" * 80)

        explanations = core.explain_discovery(
            discovery.discovery_id.split('_')[1],
            audience_level="expert"
        )

        print(f"\nExpert Explanation:")
        print(f"  {explanations['explanation']}")

        print(f"\nStudent Explanation:")
        print(f"  {explanations['all_explanations']['student']}")

        print(f"\nPublic Explanation:")
        print(f"  {explanations['all_explanations']['public']}")

    # Reflection
    print("\n3. META-COGNITIVE REFLECTION")
    print("-" * 80)

    reflection = core.reflect()

    print(f"\nCognitive State: {reflection['cognitive_state']}")
    print(f"Knowledge Gaps: {len(reflection['knowledge_gaps'])}")

    if reflection['knowledge_gaps']:
        print(f"\nTop Knowledge Gaps:")
        for gap in reflection['knowledge_gaps'][:3]:
            print(f"  • {gap.description} (priority: {gap.priority:.2f})")

    # Cognitive summary
    print("\n4. COGNITIVE SYSTEM SUMMARY")
    print("-" * 80)

    summary = core.get_cognitive_summary()

    print(f"\nCognitive Mode: {summary['cognitive_mode']}")
    print(f"Perceptions: {summary['perceptions']}")
    print(f"Insights: {summary['insights']}")
    print(f"Discoveries: {summary['discoveries']}")

    kg_stats = summary['knowledge_graph_stats']
    print(f"\nKnowledge Graph:")
    print(f"  Entities: {kg_stats['total_entities']}")
    print(f"  Relations: {kg_stats['total_relations']}")
    print(f"  Knowledge Gaps: {kg_stats['knowledge_gaps']}")

    neuro_stats = summary['neuro_symbolic_stats']
    print(f"\nNeuro-Symbolic Engine:")
    print(f"  Neural Discoveries: {neuro_stats['neural_discoveries']}")
    print(f"  Symbolic Formalizations: {neuro_stats['symbolic_formalizations']}")
    print(f"  Integrated Theories: {neuro_stats['integrated_theories']}")

    meta_report = summary['metacognitive_report']
    print(f"\nMeta-Cognition:")
    print(f"  Total Traces: {meta_report['total_traces']}")
    print(f"  Recent Success Rate: {meta_report['recent_success_rate']:.1%}")
    print(f"  Error Patterns: {meta_report['error_patterns_detected']}")
    print(f"  Methods Tracked: {meta_report['methods_tracked']}")

    print("\n" + "=" * 80)
    print("COGNITIVE CORE is operational!")
    print("ASTRA has taken a significant step toward Scientific AGI.")
    print("=" * 80)
