#!/usr/bin/env python3

# Copyright 2024-2026 Glenn J. White (The Open University / RAL Space)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
ASTRA Knowledge Base Auto-Updater
Automates KB updates to reduce administrative overhead.
Run after each research cycle: python3 kb_update.py
"""

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

BASE = Path("/shared/ASTRA")
KNOWLEDGE = BASE / "knowledge"
HYPOTHESES = BASE / "hypotheses"
LOGS = BASE / "logs"
CONFIG = BASE / "config"

def read_file(path):
    if path.exists():
        return path.read_text()
    return ""

def count_lines(path):
    if path.exists():
        return len(path.read_text().strip().split('\n'))
    return 0

def extract_hypothesis_statuses(queue_file):
    """Parse hypothesis queue and count statuses."""
    content = read_file(queue_file)
    statuses = {
        'pending': len(re.findall(r'\*\*Status\*\*: pending', content)),
        'confirmed': len(re.findall(r'\*\*Status\*\*: (?:confirmed|\*\*CONFIRMED)', content, re.I)),
        'refuted': len(re.findall(r'\*\*Status\*\*: (?:refuted|\*\*REFUTED)', content, re.I)),
        'inconclusive': len(re.findall(r'\*\*Status\*\*: (?:inconclusive|\*\*INCONCLUSIVE)', content, re.I)),
        'in-progress': len(re.findall(r'\*\*Status\*\*: in-progress', content)),
    }
    return statuses

def count_graveyard(path):
    """Count entries in graveyard."""
    content = read_file(path)
    return len(re.findall(r'^### H\d+|^### CD-\d+', content, re.M))

def update_meta_analysis():
    """Update META_ANALYSIS.md with current statistics."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    
    # Gather stats
    astro_status = extract_hypothesis_statuses(HYPOTHESES / "QUEUE.md")
    cross_status = extract_hypothesis_statuses(HYPOTHESES / "CROSSDOMAIN_QUEUE.md")
    graveyard_count = count_graveyard(HYPOTHESES / "GRAVEYARD.md")
    
    total_tested = astro_status['confirmed'] + astro_status['refuted'] + astro_status['inconclusive'] + \
                   cross_status['confirmed'] + cross_status['refuted'] + cross_status['inconclusive']
    total_confirmed = astro_status['confirmed'] + cross_status['confirmed']
    total_refuted = astro_status['refuted'] + cross_status['refuted']
    total_inconclusive = astro_status['inconclusive'] + cross_status['inconclusive']
    survival_rate = (total_confirmed / total_tested * 100) if total_tested > 0 else 0
    
    total_pending = astro_status['pending'] + cross_status['pending']
    
    # Count scripts and plots
    scripts = len(list((BASE / "pipeline").glob("*.py")))
    plots = len(list((BASE / "data" / "discovery_run" / "plots").glob("*.png"))) if (BASE / "data" / "discovery_run" / "plots").exists() else 0
    
    # Count run log entries
    log_file = LOGS / f"{datetime.now().strftime('%Y-%m')}.md"
    cycles = read_file(log_file).count("UTC — ") if log_file.exists() else 0
    
    meta = f"""# ASTRA Meta-Analysis Tracker

**Last updated**: {now}
**Total cycles**: {cycles}

---

## Hypothesis Survival Rates

### Overall
| Metric | Count |
|--------|-------|
| Total tested | {total_tested} |
| Confirmed | {total_confirmed} |
| Refuted | {total_refuted} |
| Inconclusive | {total_inconclusive} |
| Survival rate | {survival_rate:.1f}% |
| Pending | {total_pending} |
| In graveyard | {graveyard_count} |

### Astrophysics Queue
| Status | Count |
|--------|-------|
| Pending | {astro_status['pending']} |
| Confirmed | {astro_status['confirmed']} |
| Refuted | {astro_status['refuted']} |
| Inconclusive | {astro_status['inconclusive']} |

### Cross-Domain Queue
| Status | Count |
|--------|-------|
| Pending | {cross_status['pending']} |
| Confirmed | {cross_status['confirmed']} |
| Refuted | {cross_status['refuted']} |
| Inconclusive | {cross_status['inconclusive']} |

## Productivity Metrics
| Metric | Value |
|--------|-------|
| Analysis scripts | {scripts} |
| Plots generated | {plots} |
| Cycles completed | {cycles} |
| Avg cycles per hour | {cycles / max(1, 1):.1f} |

## Bias Detection
_(Updated every 5 cycles by the orchestrator)_

- [ ] Are we repeating hypothesis types?
- [ ] Are we ignoring domains?
- [ ] Are we biased toward correlation over causation?
- [ ] Are we avoiding high-risk/high-reward hypotheses?

## Recommended Focus Areas
_(Updated by orchestrator based on productivity data)_

1. TBD after sufficient data

---
*Auto-generated by kb_update.py*
"""
    
    (KNOWLEDGE / "META_ANALYSIS.md").write_text(meta)
    print(f"META_ANALYSIS.md updated: {total_tested} tested, {survival_rate:.1f}% survival rate")

def update_state_timestamp():
    """Update timestamp in STATE.md."""
    state_file = KNOWLEDGE / "STATE.md"
    content = read_file(state_file)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    content = re.sub(r'\*\*Last updated\*\*: .*', f'**Last updated**: {now}', content)
    state_file.write_text(content)
    print("STATE.md timestamp updated")

def update_queue_timestamps():
    """Update timestamps in queue files."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    for queue_file in [HYPOTHESES / "QUEUE.md", HYPOTHESES / "CROSSDOMAIN_QUEUE.md"]:
        content = read_file(queue_file)
        content = re.sub(r'\*\*Last updated\*\*: .*', f'**Last updated**: {now}', content)
        queue_file.write_text(content)
        print(f"{queue_file.name} timestamp updated")

def update_monitor():
    """Update the monitor dashboard status."""
    monitor_file = CONFIG / "monitor.md"
    if not monitor_file.exists():
        return
    
    content = read_file(monitor_file)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M UTC")
    
    # Update timestamp
    content = re.sub(r'\*Last updated:.*?\*', f'*Last updated: {now}*', content)
    
    # Update counts
    astro = extract_hypothesis_statuses(HYPOTHESES / "QUEUE.md")
    cross = extract_hypothesis_statuses(HYPOTHESES / "CROSSDOMAIN_QUEUE.md")
    total_pending = astro['pending'] + cross['pending']
    total_tested = (astro['confirmed'] + astro['refuted'] + astro['inconclusive'] +
                   cross['confirmed'] + cross['refuted'] + cross['inconclusive'])
    
    monitor_file.write_text(content)
    print(f"Monitor updated: {total_pending} pending, {total_tested} tested")

def main():
    print(f"ASTRA KB Update — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 50)
    
    update_meta_analysis()
    update_state_timestamp()
    update_queue_timestamps()
    update_monitor()
    
    # Log the update
    log_file = LOGS / f"{datetime.now().strftime('%Y-%m')}.md"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    with open(log_file, "a") as f:
        f.write(f"\n## {now} — KB Auto-Update\n")
        f.write(f"- META_ANALYSIS.md refreshed\n")
        f.write(f"- Timestamps updated across STATE, queues, monitor\n")
    
    print("=" * 50)
    print("KB update complete.")

if __name__ == "__main__":
    main()
