"""
V108 Real-Time Streaming Discovery - Online Causal Discovery and Alerting
=========================================================================

PROBLEM: Traditional discovery systems process static datasets. They cannot:
1. Detect discoveries as data arrives in real-time
2. Adapt to changing relationships over time
3. Alert astronomers to emerging patterns immediately
4. Handle streaming data from surveys (LSST, SKA)

SOLUTION: Real-Time Streaming Discovery with:
1. Online Causal Discovery - Update PAGs as new data arrives
2. Adaptive Concept Drift Detection - Detect when relationships change
3. Streaming Alert System - Real-time discovery alerts
4. Incremental Evidence Accumulation - Build confidence over time
5. Temporal Smoothing - Reduce false positives from noise

INTEGRATION:
- Extends V98 FCI for online learning
- Uses V101 temporal causal methods
- Integrates with V107 triage for alert prioritization
- Works with V4.0 MCE for context-aware streaming

USE CASES:
- Real-time transient discovery (LSST alerts)
- Streaming time-series causality (SKA pulsar data)
- Adaptive causal monitoring (observatory operations)
- Early warning for unexpected patterns

Date: 2026-04-14
Version: 1.0
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Tuple, Callable
from enum import Enum
import numpy as np
from scipy import stats
from collections import deque, defaultdict
import json
from datetime import datetime, timedelta
import warnings


class StreamingState(Enum):
    """States of streaming discovery"""
    INITIALIZING = "initializing"      # Gathering initial data
    LEARNING = "learning"              # Building causal model
    STABLE = "stable"                  # Stable causal structure
    DRIFTING = "drifting"              # Detecting concept drift
    ALERTING = "alerting"              # Discovery alert active
    RECOVERING = "recovering"          # Recovering from drift


class AlertPriority(Enum):
    """Priority levels for discovery alerts"""
    CRITICAL = "critical"              # Immediate action required
    HIGH = "high"                      # Investigate soon
    MEDIUM = "medium"                  # Monitor
    LOW = "low"                        # Informational


class ConceptDriftType(Enum):
    """Types of concept drift"""
    SUDDEN = "sudden"                  # Abrupt change
    INCREMENTAL = "incremental"        # Gradual change
    RECURRING = "recurring"            # Cyclical pattern
    BLIP = "blip"                      # Temporary fluctuation


@dataclass
class StreamingDiscoveryAlert:
    """Alert generated by streaming discovery"""
    alert_id: str
    timestamp: datetime
    priority: AlertPriority
    discovery_type: str  # "new_causal", "causal_break", "novel_correlation", etc.
    description: str
    variables: List[str]
    evidence: Dict[str, Any]
    confidence: float
    context: Dict[str, Any]
    acknowledged: bool = False


@dataclass
class ConceptDriftEvent:
    """Event representing detected concept drift"""
    drift_id: str
    timestamp: datetime
    drift_type: ConceptDriftType
    severity: float  # 0-1
    affected_variables: List[str]
    previous_structure: Dict
    new_structure: Dict
    adaptation_strategy: str


@dataclass
class StreamingDiscoveryState:
    """Current state of streaming discovery"""
    state: StreamingState
    n_observations: int
    causal_graph: Optional[Any]  # Current PAG
    confidence_scores: Dict[str, float]
    drift_history: List[ConceptDriftEvent]
    recent_alerts: List[StreamingDiscoveryAlert]
    last_update: datetime


class ConceptDriftDetector:
    """
    Detect concept drift in streaming causal relationships.

    Methods:
    - Statistical process control
    - Change point detection
    - Distribution shift detection
    - Causal structure comparison
    """

    def __init__(self, window_size: int = 100, threshold: float = 3.0):
        """
        Initialize concept drift detector.

        Args:
            window_size: Size of sliding window for statistics
            threshold: Standard deviation threshold for alert
        """
        self.window_size = window_size
        self.threshold = threshold
        self.windows: Dict[str, deque] = defaultdict(lambda: deque(maxlen=window_size))
        self.baselines: Dict[str, Tuple[float, float]] = {}  # (mean, std)

    def update_baseline(
        self,
        data: np.ndarray,
        variable_names: List[str]
    ):
        """
        Initialize baseline statistics from initial data.

        Args:
            data: Initial dataset (n_samples, n_variables)
            variable_names: Variable names
        """
        for i, var in enumerate(variable_names):
            var_data = data[:, i]
            self.baselines[var] = (np.mean(var_data), np.std(var_data))
            self.windows[var].extend(var_data[-self.window_size:])

    def detect_drift(
        self,
        new_data: np.ndarray,
        variable_names: List[str]
    ) -> List[ConceptDriftEvent]:
        """
        Detect concept drift in new data.

        Args:
            new_data: New data batch
            variable_names: Variable names

        Returns:
            List of detected drift events
        """
        drift_events = []

        for i, var in enumerate(variable_names):
            if var not in self.baselines:
                continue

            # Update window
            self.windows[var].extend(new_data[:, i])

            # Check for drift using statistical process control
            current_mean = np.mean(list(self.windows[var]))
            baseline_mean, baseline_std = self.baselines[var]

            if baseline_std > 0:
                z_score = abs(current_mean - baseline_mean) / baseline_std

                if z_score > self.threshold:
                    # Drift detected
                    drift_type = self._classify_drift_type(z_score, new_data[:, i])

                    event = ConceptDriftEvent(
                        drift_id=f"drift_{var}_{datetime.now().isoformat()}",
                        timestamp=datetime.now(),
                        drift_type=drift_type,
                        severity=min(1.0, z_score / (2 * self.threshold)),
                        affected_variables=[var],
                        previous_structure={'mean': baseline_mean, 'std': baseline_std},
                        new_structure={'mean': current_mean},
                        adaptation_strategy="rebaseline" if drift_type == ConceptDriftType.SUDDEN else "adapt"
                    )
                    drift_events.append(event)

                    # Update baseline for incremental drift
                    if drift_type == ConceptDriftType.INCREMENTAL:
                        self.baselines[var] = (current_mean, np.std(list(self.windows[var])))

        return drift_events

    def _classify_drift_type(self, z_score: float, new_data: np.ndarray) -> ConceptDriftType:
        """Classify the type of concept drift"""
        if z_score > self.threshold * 2:
            return ConceptDriftType.SUDDEN
        elif z_score > self.threshold * 1.5:
            return ConceptDriftType.INCREMENTAL
        else:
            return ConceptDriftType.BLIP

    def detect_distribution_shift(
        self,
        old_data: np.ndarray,
        new_data: np.ndarray,
        variable_names: List[str]
    ) -> Dict[str, float]:
        """
        Detect distribution shift using KS test.

        Returns:
            Dict mapping variable to p-value (low = significant shift)
        """
        shift_pvals = {}

        for i, var in enumerate(variable_names):
            if len(old_data) > 0 and len(new_data) > 0:
                # Kolmogorov-Smirnov test
                _, pval = stats.ks_2samp(old_data[:, i], new_data[:, i])
                shift_pvals[var] = pval

        return shift_pvals


class OnlineCausalDiscovery:
    """
    Online causal discovery that updates as new data arrives.

    Features:
    - Incremental PAG updates
    - Confidence accumulation
    - Edge appearance/disappearance tracking
    - Adaptive alpha levels
    """

    def __init__(
        self,
        initial_batch_size: int = 500,
        update_interval: int = 100,
        min_confidence: float = 0.7
    ):
        """
        Initialize online causal discovery.

        Args:
            initial_batch_size: Minimum samples before first discovery
            update_interval: Update PAG every N samples
            min_confidence: Minimum confidence for causal edge
        """
        self.initial_batch_size = initial_batch_size
        self.update_interval = update_interval
        self.min_confidence = min_confidence

        self.data_buffer: List[np.ndarray] = []
        self.n_samples = 0
        self.current_pag: Optional[Any] = None
        self.edge_history: Dict[Tuple[str, str], List[float]] = defaultdict(list)
        self.variable_names: List[str] = []

        # Confidence tracking
        self.edge_confidence: Dict[Tuple[str, str], float] = {}

    def process_batch(
        self,
        new_data: np.ndarray,
        variable_names: List[str]
    ) -> Optional[Any]:
        """
        Process a new batch of data and update PAG.

        Args:
            new_data: New data batch (n_samples, n_variables)
            variable_names: Variable names

        Returns:
            Updated PAG (or None if not ready)
        """
        # Initialize if first batch
        if not self.variable_names:
            self.variable_names = variable_names

        # Add data to buffer
        self.data_buffer.append(new_data)
        self.n_samples += len(new_data)

        # Check if ready for discovery
        if self.n_samples < self.initial_batch_size:
            return None

        # Check if update interval reached
        if self.n_samples % self.update_interval != 0:
            return self.current_pag

        # Perform causal discovery on accumulated data
        return self._update_pag()

    def _update_pag(self) -> Optional[Any]:
        """Update PAG using current data buffer"""
        # Combine all data
        all_data = np.vstack(self.data_buffer)

        try:
            # Try to import FCI
            from stan_core.capabilities.v98_fci_causal_discovery import FCIDiscovery
            fci = FCIDiscovery(alpha=0.05)

            # Convert numpy array to dict format expected by V98
            data_dict = {name: all_data[:, i] for i, name in enumerate(self.variable_names)}

            # Run FCI
            new_pag = fci.discover_pag(data_dict, self.variable_names)

            # Update edge history and confidence
            self._update_edge_tracking(new_pag)

            self.current_pag = new_pag

            # Trim buffer to prevent memory growth
            if len(self.data_buffer) > 10:
                self.data_buffer = self.data_buffer[-5:]

            return new_pag

        except ImportError:
            warnings.warn("FCI not available for online discovery")
            return None

    def _update_edge_tracking(self, new_pag: Any):
        """Update edge confidence tracking"""
        if not hasattr(new_pag, 'edges'):
            return

        for edge in new_pag.edges:
            key = (edge.source, edge.target)
            confidence = getattr(edge, 'confidence', 0.5)

            self.edge_history[key].append(confidence)

            # Compute running average confidence
            if len(self.edge_history[key]) > 0:
                self.edge_confidence[key] = np.mean(self.edge_history[key][-5:])

    def get_new_edges(self) -> List[Tuple[str, str]]:
        """Get edges that appeared in recent update"""
        new_edges = []

        for key, conf in self.edge_confidence.items():
            if conf >= self.min_confidence:
                # Check if this is a new edge (recently appeared)
                if len(self.edge_history[key]) <= 3:
                    new_edges.append(key)

        return new_edges

    def get_disappeared_edges(self) -> List[Tuple[str, str]]:
        """Get edges that disappeared in recent update"""
        disappeared = []

        for key, conf_history in self.edge_history.items():
            if len(conf_history) > 3:
                # Check if confidence dropped significantly
                recent_conf = np.mean(conf_history[-3:])
                old_conf = np.mean(conf_history[-6:-3])

                if old_conf > self.min_confidence and recent_conf < 0.3:
                    disappeared.append(key)

        return disappeared

    def get_edge_confidence(self, source: str, target: str) -> float:
        """Get current confidence for a causal edge"""
        return self.edge_confidence.get((source, target), 0.0)


class StreamingAlertSystem:
    """
    Real-time alert system for streaming discoveries.

    Generates and manages alerts based on:
    - New causal edges appearing
    - Causal edges disappearing
    - Concept drift events
    - Novel correlations
    """

    def __init__(self):
        """Initialize streaming alert system"""
        self.active_alerts: Dict[str, StreamingDiscoveryAlert] = {}
        self.alert_history: List[StreamingDiscoveryAlert] = []
        self.alert_rules: Dict[str, Callable] = {}

        # Register default alert rules
        self._register_default_rules()

    def _register_default_rules(self):
        """Register default alert rules"""
        self.alert_rules['new_causal_edge'] = self._check_new_causal_edge
        self.alert_rules['causal_break'] = self._check_causal_break
        self.alert_rules['concept_drift'] = self._check_concept_drift
        self.alert_rules['novel_correlation'] = self._check_novel_correlation

    def process_discovery_update(
        self,
        online_discovery: OnlineCausalDiscovery,
        drift_events: List[ConceptDriftEvent],
        data: np.ndarray,
        variable_names: List[str]
    ) -> List[StreamingDiscoveryAlert]:
        """
        Process discovery update and generate alerts.

        Args:
            online_discovery: Online causal discovery instance
            drift_events: Detected concept drift events
            data: Current data batch
            variable_names: Variable names

        Returns:
            List of new alerts
        """
        new_alerts = []

        # Check for new causal edges
        new_edges = online_discovery.get_new_edges()
        for source, target in new_edges:
            alert = self._check_new_causal_edge(
                source, target, online_discovery
            )
            if alert:
                new_alerts.append(alert)

        # Check for causal breaks
        disappeared_edges = online_discovery.get_disappeared_edges()
        for source, target in disappeared_edges:
            alert = self._check_causal_break(
                source, target, online_discovery
            )
            if alert:
                new_alerts.append(alert)

        # Check concept drift
        for drift_event in drift_events:
            alert = self._check_concept_drift(drift_event)
            if alert:
                new_alerts.append(alert)

        # Check for novel correlations
        alert = self._check_novel_correlation(data, variable_names, online_discovery)
        if alert:
            new_alerts.append(alert)

        # Store alerts
        for alert in new_alerts:
            self.active_alerts[alert.alert_id] = alert
            self.alert_history.append(alert)

        return new_alerts

    def _check_new_causal_edge(
        self,
        source: str,
        target: str,
        online_discovery: OnlineCausalDiscovery
    ) -> Optional[StreamingDiscoveryAlert]:
        """Check and generate alert for new causal edge"""
        confidence = online_discovery.get_edge_confidence(source, target)

        if confidence > 0.8:
            priority = AlertPriority.HIGH
        elif confidence > 0.6:
            priority = AlertPriority.MEDIUM
        else:
            priority = AlertPriority.LOW

        return StreamingDiscoveryAlert(
            alert_id=f"new_edge_{source}_{target}_{datetime.now().isoformat()}",
            timestamp=datetime.now(),
            priority=priority,
            discovery_type="new_causal_edge",
            description=f"New causal edge detected: {source} -> {target}",
            variables=[source, target],
            evidence={'confidence': confidence},
            confidence=confidence,
            context={'state': 'new_discovery'}
        )

    def _check_causal_break(
        self,
        source: str,
        target: str,
        online_discovery: OnlineCausalDiscovery
    ) -> Optional[StreamingDiscoveryAlert]:
        """Check and generate alert for causal relationship break"""
        return StreamingDiscoveryAlert(
            alert_id=f"causal_break_{source}_{target}_{datetime.now().isoformat()}",
            timestamp=datetime.now(),
            priority=AlertPriority.MEDIUM,
            discovery_type="causal_break",
            description=f"Causal relationship broken: {source} -> {target}",
            variables=[source, target],
            evidence={},
            confidence=0.7,
            context={'state': 'causal_change'}
        )

    def _check_concept_drift(
        self,
        drift_event: ConceptDriftEvent
    ) -> Optional[StreamingDiscoveryAlert]:
        """Check and generate alert for concept drift"""
        priority = AlertPriority.HIGH if drift_event.severity > 0.7 else AlertPriority.MEDIUM

        return StreamingDiscoveryAlert(
            alert_id=f"drift_{drift_event.drift_id}",
            timestamp=drift_event.timestamp,
            priority=priority,
            discovery_type="concept_drift",
            description=f"Concept drift detected: {drift_event.drift_type.value}",
            variables=drift_event.affected_variables,
            evidence={'severity': drift_event.severity},
            confidence=drift_event.severity,
            context={'drift_type': drift_event.drift_type.value}
        )

    def _check_novel_correlation(
        self,
        data: np.ndarray,
        variable_names: List[str],
        online_discovery: OnlineCausalDiscovery
    ) -> Optional[StreamingDiscoveryAlert]:
        """Check for novel high correlations"""
        # Compute correlation matrix
        corr_matrix = np.corrcoef(data.T)

        for i in range(len(variable_names)):
            for j in range(i+1, len(variable_names)):
                corr = corr_matrix[i, j]

                # Check for strong correlation without known causal edge
                if abs(corr) > 0.8:
                    key = (variable_names[i], variable_names[j])
                    reverse_key = (variable_names[j], variable_names[i])

                    if key not in online_discovery.edge_confidence and \
                       reverse_key not in online_discovery.edge_confidence:
                        return StreamingDiscoveryAlert(
                            alert_id=f"novel_corr_{variable_names[i]}_{variable_names[j]}_{datetime.now().isoformat()}",
                            timestamp=datetime.now(),
                            priority=AlertPriority.LOW,
                            discovery_type="novel_correlation",
                            description=f"Strong correlation without causal edge: "
                                       f"{variable_names[i]} <-> {variable_names[j]}",
                            variables=[variable_names[i], variable_names[j]],
                            evidence={'correlation': corr},
                            confidence=0.6,
                            context={'state': 'correlation_only'}
                        )

        return None

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert"""
        if alert_id in self.active_alerts:
            self.active_alerts[alert_id].acknowledged = True
            return True
        return False

    def get_active_alerts(self, priority: Optional[AlertPriority] = None) -> List[StreamingDiscoveryAlert]:
        """Get active alerts, optionally filtered by priority"""
        alerts = [a for a in self.active_alerts.values() if not a.acknowledged]

        if priority:
            alerts = [a for a in alerts if a.priority == priority]

        return sorted(alerts, key=lambda a: a.timestamp, reverse=True)

    def clear_old_alerts(self, max_age: timedelta = timedelta(hours=24)):
        """Clear alerts older than max_age"""
        cutoff = datetime.now() - max_age

        to_remove = [
            alert_id for alert_id, alert in self.active_alerts.items()
            if alert.timestamp < cutoff or alert.acknowledged
        ]

        for alert_id in to_remove:
            del self.active_alerts[alert_id]


class StreamingDiscoveryEngine:
    """
    Main orchestrator for real-time streaming discovery.

    Integrates online causal discovery, concept drift detection,
    and alert generation.
    """

    def __init__(
        self,
        variable_names: List[str],
        initial_batch_size: int = 500,
        update_interval: int = 100
    ):
        """
        Initialize streaming discovery engine.

        Args:
            variable_names: Variable names to track
            initial_batch_size: Minimum samples before first discovery
            update_interval: Update interval for causal discovery
        """
        self.variable_names = variable_names
        self.online_discovery = OnlineCausalDiscovery(
            initial_batch_size=initial_batch_size,
            update_interval=update_interval
        )
        self.drift_detector = ConceptDriftDetector()
        self.alert_system = StreamingAlertSystem()

        self.state = StreamingDiscoveryState(
            state=StreamingState.INITIALIZING,
            n_observations=0,
            causal_graph=None,
            confidence_scores={},
            drift_history=[],
            recent_alerts=[],
            last_update=datetime.now()
        )

    def process_stream_batch(
        self,
        new_data: np.ndarray
    ) -> Dict[str, Any]:
        """
        Process a new batch of streaming data.

        Args:
            new_data: New data batch (n_samples, n_variables)

        Returns:
            Processing results with alerts and updates
        """
        # Update state
        self.state.n_observations += len(new_data)
        self.state.last_update = datetime.now()

        # Initialize baseline if first batch
        if self.state.state == StreamingState.INITIALIZING:
            if len(new_data) >= self.online_discovery.initial_batch_size:
                self.drift_detector.update_baseline(new_data, self.variable_names)
                self.state.state = StreamingState.LEARNING

        # Detect concept drift
        drift_events = self.drift_detector.detect_drift(new_data, self.variable_names)
        self.state.drift_history.extend(drift_events)

        # Update causal discovery
        updated_pag = self.online_discovery.process_batch(new_data, self.variable_names)
        if updated_pag:
            self.state.causal_graph = updated_pag

        # Generate alerts
        new_alerts = self.alert_system.process_discovery_update(
            self.online_discovery,
            drift_events,
            new_data,
            self.variable_names
        )
        self.state.recent_alerts.extend(new_alerts)

        # Update state based on alerts
        if new_alerts:
            critical_alerts = [a for a in new_alerts if a.priority == AlertPriority.CRITICAL]
            if critical_alerts:
                self.state.state = StreamingState.ALERTING

        # Update confidence scores
        self._update_confidence_scores()

        return {
            'state': self.state.state.value,
            'n_observations': self.state.n_observations,
            'updated_pag': updated_pag is not None,
            'drift_events': drift_events,
            'new_alerts': new_alerts,
            'active_alerts': self.alert_system.get_active_alerts(),
            'confidence_scores': self.state.confidence_scores
        }

    def _update_confidence_scores(self):
        """Update confidence scores for all edges"""
        if not self.state.causal_graph:
            return

        if hasattr(self.state.causal_graph, 'edges'):
            for edge in self.state.causal_graph.edges:
                key = (edge.source, edge.target)
                conf = self.online_discovery.get_edge_confidence(edge.source, edge.target)
                self.state.confidence_scores[key] = conf

    def get_current_state(self) -> StreamingDiscoveryState:
        """Get current streaming discovery state"""
        return self.state

    def get_alert_summary(self) -> str:
        """Get summary of current alerts"""
        active_alerts = self.alert_system.get_active_alerts()

        lines = []
        lines.append("=== STREAMING DISCOVERY ALERTS ===\n")
        lines.append(f"Observations: {self.state.n_observations}")
        lines.append(f"State: {self.state.state.value}\n")

        if active_alerts:
            lines.append(f"Active Alerts: {len(active_alerts)}\n")
            for alert in active_alerts[:10]:  # Show first 10
                lines.append(f"[{alert.priority.value.upper()}] {alert.description}")
        else:
            lines.append("No active alerts")

        return "\n".join(lines)


# Factory functions

def create_streaming_discovery_engine(
    variable_names: List[str],
    initial_batch_size: int = 500,
    update_interval: int = 100
) -> StreamingDiscoveryEngine:
    """Factory function to create StreamingDiscoveryEngine"""
    return StreamingDiscoveryEngine(
        variable_names=variable_names,
        initial_batch_size=initial_batch_size,
        update_interval=update_interval
    )


def create_online_causal_discovery(
    initial_batch_size: int = 500,
    update_interval: int = 100
) -> OnlineCausalDiscovery:
    """Factory function to create OnlineCausalDiscovery"""
    return OnlineCausalDiscovery(
        initial_batch_size=initial_batch_size,
        update_interval=update_interval
    )


def create_streaming_alert_system() -> StreamingAlertSystem:
    """Factory function to create StreamingAlertSystem"""
    return StreamingAlertSystem()


# Convenience function

def monitor_streaming_data(
    data_stream: np.ndarray,
    variable_names: List[str],
    batch_size: int = 100
) -> Dict[str, Any]:
    """
    Monitor streaming data for real-time discoveries.

    Args:
        data_stream: Streaming data (n_total_samples, n_variables)
        variable_names: Variable names
        batch_size: Batch size for processing

    Returns:
        Complete monitoring results
    """
    engine = create_streaming_discovery_engine(variable_names)

    all_results = []
    all_alerts = []

    # Process data in batches
    for i in range(0, len(data_stream), batch_size):
        batch = data_stream[i:i+batch_size]

        if len(batch) > 0:
            result = engine.process_stream_batch(batch)
            all_results.append(result)
            all_alerts.extend(result.get('new_alerts', []))

    return {
        'processing_results': all_results,
        'all_alerts': all_alerts,
        'final_state': engine.get_current_state(),
        'alert_summary': engine.get_alert_summary(),
        'total_discoveries': len([r for r in all_results if r.get('updated_pag')])
    }
