"""
V7.0 Shared Types

Common data types used across V7.0 components to avoid circular imports.
"""

import numpy as np
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime


class ResearchCycle(Enum):
    """Stages of the research cycle"""
    QUESTION = "question"
    HYPOTHESIS = "hypothesis"
    DESIGN = "design"
    EXPERIMENT = "experiment"
    ANALYSIS = "analysis"
    THEORY = "theory"
    PUBLICATION = "publication"


class QuestionType(Enum):
    """Types of research questions"""
    OBSERVATIONAL = "observational"
    THEORETICAL = "theoretical"
    EXPERIMENTAL = "experimental"
    COMPUTATIONAL = "computational"
    INTERDISCIPLINARY = "interdisciplinary"
    METHODOLOGICAL = "methodological"


class QuestionImportance(Enum):
    """Importance levels for questions"""
    TRANSFORMATIVE = 5
    MAJOR = 4
    MODERATE = 3
    MINOR = 2
    TECHNICAL = 1


class HypothesisType(Enum):
    """Types of hypotheses"""
    THEORETICAL = "theoretical"
    EMPIRICAL = "empirical"
    CAUSAL = "causal"
    ANALOGICAL = "analogical"
    EXPLANATORY = "explanatory"
    PREDICTIVE = "predictive"


class HypothesisStatus(Enum):
    """Status of hypothesis testing"""
    PROPOSED = "proposed"
    TESTING = "testing"
    CONFIRMED = "confirmed"
    REFUTED = "refuted"
    INCONCLUSIVE = "inconclusive"


class ExperimentType(Enum):
    """Types of experiments"""
    OBSERVATIONAL = "observational"
    SIMULATION = "simulation"
    LABORATORY = "laboratory"
    ANALYSIS = "analysis"
    SURVEY = "survey"


@dataclass
class ResearchQuestion:
    """A research question generated by ASTRA"""
    question: str
    question_type: QuestionType
    importance: QuestionImportance
    domain: str
    context: Dict[str, Any]
    motivation: str
    feasibility: float
    expected_impact: float
    references: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class Hypothesis:
    """A scientific hypothesis"""
    statement: str
    hypothesis_type: HypothesisType
    status: HypothesisStatus
    predictions: List[str]
    test_method: str
    required_data: List[str]
    theoretical_basis: List[str]
    confidence: float
    novelty_score: float
    created_at: datetime = field(default_factory=datetime.now)


@dataclass
class DesignParameters:
    """Parameters for experimental design"""
    targets: List[str]
    instruments: List[str]
    exposure_time: float
    spectral_resolution: Optional[float] = None
    spatial_resolution: Optional[float] = None
    wavelength_range: Optional[tuple] = None
    cadence: Optional[float] = None
    total_duration: str = "standard"


@dataclass
class Experiment:
    """An experimental design"""
    name: str
    experiment_type: ExperimentType
    objective: str
    design: DesignParameters
    predicted_outcome: str
    required_resources: List[str]
    estimated_cost: float
    estimated_duration: str
    success_criteria: List[str]
    created_at: datetime = field(default_factory=datetime.now)


class DataSource(Enum):
    """Types of data sources"""
    ARCHIVE = "archive"
    TELESCOPE = "telescope"
    SIMULATION = "simulation"
    LABORATORY = "laboratory"
    DATABASE = "database"


@dataclass
class ExecutionResult:
    """Results from experiment execution"""
    experiment_name: str
    source: DataSource
    success: bool
    data: Any
    metadata: Dict[str, Any]
    errors: List[str]
    execution_time: float
    success_rate: float
    logs: List[str]


class PredictionType(Enum):
    OBSERVATIONAL = "observational"
    THEORETICAL = "theoretical"
    STATISTICAL = "statistical"
    CAUSAL = "causal"


class PredictionConfidence(Enum):
    HIGH = 0.9
    MODERATE = 0.7
    LOW = 0.5
    SPECULATIVE = 0.3


class AnalysisType(Enum):
    STATISTICAL = "statistical"
    CAUSAL = "causal"
    MULTISCALE = "multiscale"
    COMPARATIVE = "comparative"


@dataclass
class CausalInferenceResult:
    """Results from causal inference"""
    causal_structure: Dict[str, Any]
    confounders: List[str]
    effect_sizes: Dict[str, float]
    confidence_intervals: Dict[str, tuple]
    interventions: List[Dict]


class RevisionType(Enum):
    PARAMETER_UPDATE = "parameter_update"
    STRUCTURAL_CHANGE = "structural_change"
    NEW_PHYSICS = "new_physics"
    APPROXIMATION = "approximation"


class TheoryStatus(Enum):
    CONFIRMED = "confirmed"
    REFUTED = "refuted"
    REVISED = "revised"
    UNCERTAIN = "uncertain"


class PaperStructure(Enum):
    STANDARD = "standard"
    LETTER = "letter"
    REVIEW = "review"
    METHODS = "methods"


class FigureType(Enum):
    DATA_PLOT = "data_plot"
    SCHEMATIC = "schematic"
    DIAGRAM = "diagram"
    COMPARISON = "comparison"


@dataclass
class ResearchResult:
    """Results from research execution"""
    experiment_name: str
    execution_result: ExecutionResult
    analysis_results: Dict[str, Any]
    predictions_validated: List[str]
    predictions_refuted: List[str]
    new_discoveries: List[str]
    confidence: float
    completed_at: datetime = field(default_factory=datetime.now)


@dataclass
class Publication:
    """A publication-ready paper"""
    title: str
    abstract: str
    authors: List[str]
    structure: PaperStructure
    figures: List[Dict[str, Any]]
    tables: List[Dict[str, Any]]
    references: List[str]
    target_journal: str
    publication_status: str
    created_at: datetime = field(default_factory=datetime.now)


__all__ = [
    # Enums
    'ResearchCycle',
    'QuestionType',
    'QuestionImportance',
    'HypothesisType',
    'HypothesisStatus',
    'ExperimentType',
    'DataSource',
    'PredictionType',
    'PredictionConfidence',
    'AnalysisType',
    'CausalInferenceResult',
    'RevisionType',
    'TheoryStatus',
    'PaperStructure',
    'FigureType',
    # Data classes
    'ResearchQuestion',
    'Hypothesis',
    'DesignParameters',
    'Experiment',
    'ExecutionResult',
    'ResearchResult',
    'Publication',
]
