#!/usr/bin/env python3
"""Generate a LaTeX supplement document from ASTRA's validated hypotheses.

Usage:
    python generate_supplement.py [--api URL] [--output FILE] [--all-phases]
    python generate_supplement.py --all-phases          # include all hypothesis phases
    python generate_supplement.py --output supplement.tex
"""

import argparse
import json
import os
import re
import subprocess
import sys
import textwrap
import time
from datetime import datetime, timezone
from urllib.request import urlopen, Request
from urllib.error import URLError


# ── Helpers ──────────────────────────────────────────────────────

def api_get(base_url: str, endpoint: str):
    """GET JSON from ASTRA API."""
    url = f"{base_url.rstrip('/')}{endpoint}"
    try:
        req = Request(url, headers={"Accept": "application/json"})
        with urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())
    except Exception as e:
        return None


def tex_escape(text: str) -> str:
    """Escape LaTeX special characters."""
    if not text:
        return ""
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    # Handle backslash first
    text = text.replace('\\', r'\textbackslash{}')
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def format_pvalue(p: float) -> str:
    """Format p-value for LaTeX."""
    if p is None:
        return "---"
    if p < 1e-10:
        return f"$< 10^{{-10}}$"
    if p < 0.001:
        exp = int(f"{p:.1e}".split("e")[1])
        mantissa = p / (10 ** exp)
        return f"${mantissa:.1f} \\times 10^{{{exp}}}$"
    return f"${p:.4f}$"


def format_stat(s: float) -> str:
    """Format a test statistic."""
    if s is None:
        return "---"
    if abs(s) > 1000:
        return f"${s:.1f}$"
    return f"${s:.4f}$"


def phase_badge(phase: str) -> str:
    """Return a LaTeX-formatted phase indicator."""
    phase_map = {
        "proposed": r"\textsc{proposed}",
        "screening": r"\textsc{screening}",
        "testing": r"\textsc{testing}",
        "validated": r"\textbf{validated}",
        "published": r"\textbf{\textsc{published}}",
        "archived": r"\textit{archived}",
    }
    return phase_map.get(phase.lower(), tex_escape(phase))


# ── LaTeX Generation ─────────────────────────────────────────────

def generate_preamble(n_hypotheses: int, n_discoveries: int,
                      include_all: bool) -> str:
    """Generate the LaTeX preamble and title page."""
    phase_note = "all phases" if include_all else "validated and published phases"
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return textwrap.dedent(rf"""
    % ASTRA Supplementary Material — Auto-generated by generate_supplement.py
    % Generated: {timestamp}
    \documentclass[fleqn,usenatbib]{{mnras}}

    \usepackage{{newtxtext,newtxmath}}
    \usepackage{{longtable}}
    \usepackage{{booktabs}}
    \usepackage{{graphicx}}
    \usepackage{{xcolor}}
    \usepackage{{hyperref}}

    \definecolor{{astra-cyan}}{{HTML}}{{00E5FF}}
    \definecolor{{astra-amber}}{{HTML}}{{FFAB00}}

    \title[]{{ASTRA: Supplementary Material --- Full Hypothesis Catalogue}}

    \author[White \& Dey]{{
    Glenn~J.~White$^{{1,2}}$\thanks{{E-mail: glenn.white@open.ac.uk}}
    and Robin~Dey$^{{3}}$
    \\
    $^{{1}}$School of Physical Sciences, The Open University, Milton Keynes MK7 6AA, UK\\
    $^{{2}}$RAL Space, STFC Rutherford Appleton Laboratory, Chilton, Didcot OX11 0QX, UK\\
    $^{{3}}$VBRL Holdings Inc.
    }}

    \date{{Generated {timestamp}}}

    \begin{{document}}
    \maketitle

    \begin{{abstract}}
    This supplementary document catalogues all hypotheses investigated by the
    ASTRA (Autonomous Science \& Technology Research Agent) framework,
    including statistical evidence, data provenance, and discovery records.
    It covers {n_hypotheses} hypotheses ({phase_note}) and
    {n_discoveries} discovery records from the autonomous discovery engine.
    \end{{abstract}}

    \tableofcontents
    """).strip() + "\n\n"


def generate_summary_table(hypotheses: list) -> str:
    """Generate a summary longtable of all hypotheses."""
    lines = [
        r"\section{Hypothesis Summary}",
        r"\label{sec:summary}",
        "",
        r"Table~\ref{tab:summary} provides an overview of all hypotheses in this supplement.",
        "",
        r"\begin{longtable}{lp{4cm}llrl}",
        r"\caption{Summary of ASTRA hypotheses. Confidence is the posterior probability",
        r"after Bayesian updating from statistical tests.}",
        r"\label{tab:summary} \\",
        r"\toprule",
        r"ID & Name & Domain & Phase & Conf. & Tests \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"ID & Name & Domain & Phase & Conf. & Tests \\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{6}{r}{\textit{Continued on next page}} \\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]

    for h in hypotheses:
        hid = tex_escape(h.get("id", ""))
        name = tex_escape(h.get("name", ""))[:40]
        domain = tex_escape(h.get("domain", ""))
        phase = phase_badge(h.get("phase", ""))
        conf = h.get("confidence", 0)
        n_tests = len(h.get("test_results", []))
        lines.append(
            f"  {hid} & {name} & {domain} & {phase} & "
            f"${conf:.2f}$ & {n_tests} \\\\"
        )

    lines.append(r"\end{longtable}")
    lines.append("")
    return "\n".join(lines)


def generate_hypothesis_section(h: dict, discoveries: list) -> str:
    """Generate a LaTeX subsection for a single hypothesis."""
    hid = h.get("id", "unknown")
    name = h.get("name", "Untitled")
    desc = h.get("description", "No description provided.")
    domain = h.get("domain", "Unknown")
    phase = h.get("phase", "unknown")
    conf = h.get("confidence", 0)
    data_pts = h.get("data_points_used", 0)
    tests = h.get("test_results", [])
    links = h.get("cross_domain_links", [])

    # Find discoveries linked to this hypothesis
    linked_disc = [d for d in discoveries if d.get("hypothesis_id") == hid]

    lines = [
        f"\\subsection{{{tex_escape(name)} ({tex_escape(hid)})}}",
        f"\\label{{sec:{hid.lower().replace(' ', '-')}}}",
        "",
        f"\\noindent\\textbf{{Domain:}} {tex_escape(domain)} \\hfill "
        f"\\textbf{{Phase:}} {phase_badge(phase)} \\hfill "
        f"\\textbf{{Confidence:}} ${conf:.3f}$",
        "",
        f"\\paragraph{{Description.}} {tex_escape(desc)}",
        "",
    ]

    # Data provenance
    if data_pts > 0:
        lines.append(f"\\paragraph{{Data.}} {data_pts:,} data points used in analysis.")
        lines.append("")

    # Statistical evidence table
    if tests:
        lines.extend([
            r"\paragraph{Statistical Evidence.}",
            "",
            r"\begin{table}[h]",
            r"\centering",
            f"\\caption{{Test results for {tex_escape(name)}.}}",
            f"\\label{{tab:tests-{hid.lower()}}}",
            r"\begin{tabular}{lrrl}",
            r"\toprule",
            r"Test & Statistic & $p$-value & Result \\",
            r"\midrule",
        ])

        for t in tests:
            tname = tex_escape(t.get("test_name", "Unknown"))
            stat = format_stat(t.get("statistic"))
            pval = format_pvalue(t.get("p_value"))
            passed = r"\checkmark" if t.get("passed") else r"$\times$"
            lines.append(f"  {tname} & {stat} & {pval} & {passed} \\\\")

        lines.extend([
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{table}",
            "",
        ])
    else:
        lines.append("\\paragraph{Statistical Evidence.} No statistical tests recorded yet.")
        lines.append("")

    # Cross-domain links
    if links:
        lines.append("\\paragraph{Cross-Domain Links.}")
        link_strs = [tex_escape(str(l)) for l in links]
        lines.append(", ".join(link_strs) + ".")
        lines.append("")

    # Linked discoveries
    if linked_disc:
        lines.append("\\paragraph{Associated Discoveries.}")
        lines.append(r"\begin{itemize}")
        for d in linked_disc:
            did = tex_escape(d.get("id", ""))
            ddesc = tex_escape(d.get("description", ""))[:100]
            dtype = tex_escape(d.get("finding_type", ""))
            dsrc = tex_escape(d.get("data_source", ""))
            lines.append(
                f"  \\item \\textbf{{{did}}} ({dtype}, {dsrc}): {ddesc}"
            )
        lines.append(r"\end{itemize}")
        lines.append("")

    return "\n".join(lines)


def generate_discovery_appendix(discoveries: list) -> str:
    """Generate a discovery log appendix."""
    if not discoveries:
        return ""

    lines = [
        r"\appendix",
        r"\section{Discovery Log}",
        r"\label{sec:discovery-log}",
        "",
        f"The ASTRA engine recorded {len(discoveries)} discoveries during autonomous operation.",
        "",
        r"\begin{longtable}{llllrl}",
        r"\caption{Full discovery log from ASTRA's autonomous operation.}",
        r"\label{tab:discoveries} \\",
        r"\toprule",
        r"ID & Type & Domain & Source & Statistic & $p$-value \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"ID & Type & Domain & Source & Statistic & $p$-value \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endlastfoot",
    ]

    for d in discoveries:
        did = tex_escape(d.get("id", ""))
        dtype = tex_escape(d.get("finding_type", ""))
        domain = tex_escape(d.get("domain", ""))
        source = tex_escape(d.get("data_source", ""))
        stat = format_stat(d.get("statistic"))
        pval = format_pvalue(d.get("p_value"))
        lines.append(f"  {did} & {dtype} & {domain} & {source} & {stat} & {pval} \\\\")

    lines.extend([
        r"\end{longtable}",
        "",
        # Individual discovery details
        r"\subsection{Discovery Details}",
        "",
    ])

    for d in discoveries:
        did = d.get("id", "")
        desc = d.get("description", "No description.")
        variables = d.get("variables", [])
        if isinstance(variables, str):
            try:
                variables = json.loads(variables)
            except Exception:
                variables = [variables]

        strength = d.get("strength", 0)
        effect = d.get("effect_size")

        lines.append(f"\\paragraph{{{tex_escape(did)}: {tex_escape(d.get('finding_type', ''))} "
                      f"({tex_escape(d.get('data_source', ''))}).}}")
        lines.append(f"{tex_escape(desc[:200])}")
        if variables:
            var_str = ", ".join(tex_escape(str(v)) for v in variables)
            lines.append(f" Variables: {var_str}.")
        if strength:
            lines.append(f" Strength: ${strength:.3f}$.")
        if effect is not None:
            lines.append(f" Effect size: ${effect:.4f}$.")
        lines.append("")

    return "\n".join(lines)


def generate_postamble() -> str:
    """Close the document."""
    return textwrap.dedent(r"""
    \section*{Acknowledgements}
    This supplement was auto-generated by the ASTRA framework's
    \texttt{generate\_supplement.py} script.
    The ASTRA project is available at
    \url{https://github.com/Tilanthi/ASTRA}.

    \end{document}
    """).strip() + "\n"


# ── Main ─────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate a LaTeX supplement document from ASTRA hypotheses.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
        Examples:
          python generate_supplement.py                    # validated/published only
          python generate_supplement.py --all-phases       # include all phases
          python generate_supplement.py --output out.tex   # custom output path
          python generate_supplement.py --compile          # also run pdflatex
        """),
    )
    parser.add_argument("--api", default="http://localhost:8787",
                        help="ASTRA API base URL (default: http://localhost:8787)")
    parser.add_argument("--output", "-o", default="/shared/ASTRA/supplement.tex",
                        help="Output LaTeX file (default: /shared/ASTRA/supplement.tex)")
    parser.add_argument("--all-phases", action="store_true",
                        help="Include hypotheses in all phases, not just validated/published")
    parser.add_argument("--compile", action="store_true",
                        help="Attempt to compile with pdflatex after generation")
    parser.add_argument("--db", default="/workspace/astra_discoveries.db",
                        help="Path to discoveries SQLite DB (for discovery log)")

    args = parser.parse_args()

    BOLD = "\033[1m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    RED = "\033[31m"
    CYAN = "\033[36m"
    RESET = "\033[0m"

    print(f"{BOLD}{'='*60}{RESET}")
    print(f"{BOLD}  ASTRA Paper Supplement Generator{RESET}")
    print(f"{'='*60}")
    print()

    # ── Fetch hypotheses from API ────────────────────────────────
    print(f"{CYAN}Fetching hypotheses from {args.api}...{RESET}")
    hypotheses_data = api_get(args.api, "/api/hypotheses")

    if hypotheses_data is None:
        print(f"{RED}ERROR: Could not connect to ASTRA API at {args.api}{RESET}")
        print(f"Make sure the server is running: python -m uvicorn astra_live_backend.server:app --port 8787")
        sys.exit(1)

    all_hypotheses = hypotheses_data if isinstance(hypotheses_data, list) else []
    print(f"  Found {len(all_hypotheses)} total hypotheses")

    # Filter by phase
    if args.all_phases:
        selected = all_hypotheses
        print(f"  Including all phases")
    else:
        validated_phases = {"validated", "published"}
        selected = [h for h in all_hypotheses if h.get("phase", "").lower() in validated_phases]
        if not selected:
            print(f"{YELLOW}  No validated/published hypotheses found.{RESET}")
            print(f"  Falling back to testing-phase hypotheses as examples.")
            selected = [h for h in all_hypotheses
                        if h.get("phase", "").lower() in {"testing", "validated", "published"}]
            if not selected:
                print(f"  Using all hypotheses.")
                selected = all_hypotheses

    print(f"  Selected {len(selected)} hypotheses for supplement")

    # Sort by ID
    selected.sort(key=lambda h: h.get("id", ""))

    # ── Fetch discoveries ────────────────────────────────────────
    print(f"{CYAN}Fetching discoveries...{RESET}")
    discoveries = []

    # Try API first
    disc_data = api_get(args.api, "/api/discovery/discoveries")
    if disc_data and isinstance(disc_data, dict):
        discoveries = disc_data.get("discoveries", [])
    elif disc_data and isinstance(disc_data, list):
        discoveries = disc_data

    # Also try DB directly
    if not discoveries and os.path.exists(args.db):
        import sqlite3
        try:
            conn = sqlite3.connect(args.db)
            conn.row_factory = sqlite3.Row
            rows = conn.execute("SELECT * FROM discoveries ORDER BY timestamp").fetchall()
            discoveries = [dict(r) for r in rows]
            conn.close()
        except Exception as e:
            print(f"  {YELLOW}DB read warning: {e}{RESET}")

    print(f"  Found {len(discoveries)} discovery records")

    # ── Generate LaTeX ───────────────────────────────────────────
    print(f"\n{CYAN}Generating LaTeX...{RESET}")

    parts = []
    parts.append(generate_preamble(len(selected), len(discoveries), args.all_phases))
    parts.append(generate_summary_table(selected))

    parts.append(r"\section{Hypothesis Details}")
    parts.append(r"\label{sec:details}")
    parts.append("")
    parts.append("Each subsection presents a hypothesis investigated by ASTRA,")
    parts.append("including its statistical evidence, data provenance, and any")
    parts.append("associated discoveries.\n")

    for h in selected:
        parts.append(generate_hypothesis_section(h, discoveries))

    if discoveries:
        parts.append(generate_discovery_appendix(discoveries))

    parts.append(generate_postamble())

    latex_content = "\n".join(parts)

    # ── Write output ─────────────────────────────────────────────
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(latex_content)

    n_lines = latex_content.count("\n") + 1
    n_bytes = len(latex_content.encode())
    print(f"  {GREEN}Written {args.output}{RESET}")
    print(f"  {n_lines} lines, {n_bytes:,} bytes")
    print(f"  {len(selected)} hypothesis sections")
    if discoveries:
        print(f"  {len(discoveries)} discovery records in appendix")

    # ── Compile if requested ─────────────────────────────────────
    if args.compile:
        print(f"\n{CYAN}Compiling with pdflatex...{RESET}")
        outdir = os.path.dirname(args.output) or "."
        texfile = os.path.basename(args.output)
        try:
            for i in range(2):  # Two passes for TOC/refs
                result = subprocess.run(
                    ["pdflatex", "-interaction=nonstopmode",
                     "-output-directory", outdir, texfile],
                    cwd=outdir,
                    capture_output=True, text=True, timeout=60,
                )
                if result.returncode != 0 and i == 1:
                    print(f"  {YELLOW}pdflatex warnings (may be OK):{RESET}")
                    # Show last few error lines
                    for line in result.stdout.split("\n"):
                        if line.startswith("!") or "Error" in line:
                            print(f"    {line}")

            pdf_path = args.output.replace(".tex", ".pdf")
            if os.path.exists(pdf_path):
                pdf_size = os.path.getsize(pdf_path)
                print(f"  {GREEN}PDF generated: {pdf_path} ({pdf_size:,} bytes){RESET}")
            else:
                print(f"  {YELLOW}PDF not generated — check log file{RESET}")
        except FileNotFoundError:
            print(f"  {YELLOW}pdflatex not found — install texlive-latex-base{RESET}")
        except subprocess.TimeoutExpired:
            print(f"  {RED}pdflatex timed out{RESET}")

    print(f"\n{BOLD}{'='*60}{RESET}")
    print(f"{GREEN}Supplement generation complete!{RESET}")
    print(f"{'='*60}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
